#!/bin/bash
# install_jenkins.sh 
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
    https://pkg.jenkins.io/debian/jenkins.io-2023.key
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
    https://pkg.jenkins.io/debian binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install fontconfig openjdk-17-jre
sudo apt-get install jenkins

#install docker
sudo apt update
sudo apt install docker.io
sudo systemctl start docker
sudo systemctl enable docker
sudo docker pull sonarqube
sudo docker run -d -p 9000:9000 sonarqube

#install trivy
sudo apt-get install wget apt-transport-https gnupg lsb-release
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
sudo apt-get update
sudo apt-get install trivy

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}


provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "amazon_clone_vpc" {
  cidr_block = "10.0.0.0/16"
  instance_tenancy = "default"

  tags = {
    Name = "amazon-clone-vpc"
  }
}

resource "aws_subnet" "amazon_clone_subnet" {
  vpc_id            = aws_vpc.amazon_clone_vpc.id
  cidr_block        = "10.0.1.0/24"
  availability_zone = "us-east-1a"

  tags = {
    Name = "amazon-clone-subnet"
  }
}

resource "aws_internet_gateway" "amazon_clone_igw" {
  vpc_id = aws_vpc.amazon_clone_vpc.id

  tags = {
    Name = "amazon-clone-igw"
  }
}

resource "aws_security_group" "amazon_clone_sg" {
  name        = "amazon-clone-sg"
  description = "Allow TLS inbound traffic"
  vpc_id      = aws_vpc.amazon_clone_vpc.id

  ingress = [
    for port in [22, 80, 443, 8080, 9000] : {
        from_port        = port
        to_port          = port
        protocol         = "tcp"
        cidr_blocks      = ["0.0.0.0/0"]
        ipv6_cidr_blocks = []
        prefix_list_ids  = []
        security_groups  = []
        self             = false
    }
  ]

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "amazon-clone-sg"
  }
}

resource "aws_instance" "amazon_clone_instance" {
  ami                          = "ami-005fc0f236362e99f"
  instance_type                = "t2.large"
  subnet_id                    = aws_subnet.amazon_clone_subnet.id
  vpc_security_group_ids       = [aws_security_group.amazon_clone_sg.id]
  user_data                    = templatefile("./install_jenkins.sh", {})
  associate_public_ip_address  = true
  key_name                     = "NorthVirginia-PPK-12"

  tags = {
    Name = "amazon-clone-instance"
  }
}
